#!/usr/bin/env bash
mkdir -p dist
echo "build src/index.ls -> dist/cubic.js ..."
./node_modules/.bin/lsc -cbp src/index.ls > dist/cubic.js
echo "minifying cubic.js ..."
./node_modules/.bin/uglifyjs dist/cubic.js > dist/cubic.min.js
echo "done."
